### ISSUE TITLE
value argument in clean_coordinates function

### ISSUE THREAD

**Issue by nancyjpeterson** [ropensci/CoordinateCleaner#22]
In the function description for the clean_coordinates function under "value" it says:
a character string defining the output value. See the value section for details. one of ‘spatialvalid’, ‘summary’, ‘cleaned’. Default = ‘spatialvalid’.

But if you type in 'cleaned' it will throw an error. Typing 'clean' (without the 'ed') works, though.

**Comment by azizka** [comment]
Updated the documentation, thanks!
