### ISSUE TITLE
cc_outl throws error when all splist[test >= min_occs]

### ISSUE THREAD

**Issue by pepbioalerts** [ropensci/CoordinateCleaner#28]
when all species in the dataset do not pass the test of minimum occurrences
  splist <- splist[test >= min_occs]
it returns a list without elements. The function is able to warn you and continue, however, if the method is quantile and there's a sampling threshold set (sampling_thresh > 0 ) then it troughs an error. 

I have resolved the issue by adding 
if (sampling_thresh > 0 & length(flags)>0) {}

Just a suggestion
Cheers,
Pep

**Comment by azizka** [comment]
I could not reproduce it, but changes the structure of the if considition, so that this will not occur anymore as of version 2.0-14. Thanks
