### ISSUE TITLE
Raster approximation (ras_create) results in out of bounds raster object (ras) when using the cc_outl function.

### ISSUE THREAD

**Issue by winandh** [ropensci/CoordinateCleaner#31]
When using the cc_outl (Outliers) function the ras_create function can create raster objects with an extent bigger than the original extent of the input file. Any occurrences at the edges (in my case at lat = -90) can cause out of bound issues. As far as I know this can only occur when the set of occurrences > 10000 and thinning is false.

**Comment by azizka** [comment]
Thanks. I added a test for out of bound issues to the function in version 2.0.14
