### ISSUE TITLE
Should consider adding GeoLocate centroids to countryref.rda

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/CoordinateCleaner#37]
I have found that the webservice [geolocate](http://geo-locate.org/webservices/) is a large source of centroids on GBIF.  https://github.com/gbif/portal-feedback/issues/2428

Not all of these centroids are found within countryref.rda 
https://github.com/jhnwllr/gbif_shapefile_geocoder/blob/master/shapefile_making_R_scripts/plots/centroids/combined.pdf

**Comment by azizka** [comment]
yes, good idea. Can you provide the missing centroids as .rda or .txt file with the respective ISO3 code? Thanks!

**Comment by jhnwllr** [comment]
I put centroids from geolocate here: 
https://github.com/jhnwllr/gbif_shapefile_geocoder/blob/master/shapefile_making_R_scripts/data/geolocate_centroids.rda

I got the centroids by running this script on the geolocate look up service:
https://github.com/jhnwllr/gbif_shapefile_geocoder/blob/master/shapefile_making_R_scripts/shapefile_generator.r#L3-L102

**Comment by azizka** [comment]
Thanks! the file is not working for me for some obscure reason. Could you provide them as a .txt?

**Comment by jhnwllr** [comment]
try with `readRDS`

**Comment by MattBlissett** [comment]
I converted them into basic SQL, which I'm sure you can change with a quick search-replace into whatever you need: https://github.com/gbif/geocode/blob/master/database/geolocate_centroids.sql

**Comment by azizka** [comment]
Finally implemented in v2.0.17. Thanks to @jhnwllr and @MattBlissett.
