### ISSUE TITLE
An error when selecting columns of interest

### ISSUE THREAD

**Issue by evoyeyo** [ropensci/CoordinateCleaner#44]
Dear Alexander,

I was following the tutorial, and received an error at this step:

> #Select columns of interest
> dat = dat %>%
>   dplyr::select(species, decimalLongitude, decimalLatitude, countryCode, individualCount,
>                 gbifID, family, taxonRank, coordinateUncertaintyInMeters, year,
>                 basisOfRecord, institutionCode, datasetName)
> 
> **Error: `x` must be a vector, not a `tbl_df/tbl/data.frame/gbif` object.**

I have tried to solve it with https://github.com/tidyverse/dplyr/issues/5301, but couldn't find any solution so far.

Thanks in advance for any suggestion!

**Comment by azizka** [comment]
I'll close this now.
