### ISSUE TITLE
Trouble installing the CoordinateCleaner package

### ISSUE THREAD

**Issue by abalamur** [ropensci/CoordinateCleaner#45]
I tried doing 
`install.packages("CoordinateCleaner`
and then 
`library(CoordinateCleaner)`

However, I am getting this error when I try to run the library
`Error: package or namespace load failed for ‘CoordinateCleaner’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘sf’`

**Comment by azizka** [comment]
Hi,

try to install sf before: `install.packages("sf")`

**Comment by azizka** [comment]
Did this work?
