### ISSUE TITLE
Error "CRS object has comment, which is lost in output"

### ISSUE THREAD

**Issue by jamiethompson77** [ropensci/CoordinateCleaner#46]
With this code:

"flags = clean_coordinates(x = dat, lon = "decimalLongitude", lat = "decimalLatitude",
                           countries = "countryCode", 
                           species = "species",
                           tests = c("capitals", "centroids", "equal","gbif", "institutions",
                                     "zeros", "countries"),
                          country_ref=world)"

I get this error:

"Testing country identity

Warning messages:
1: In sp::proj4string(ref) :
  CRS object has comment, which is lost in output
2: In sp::proj4string(ref) :
  CRS object has comment, which is lost in output"

**Comment by azizka** [comment]
This warning is related to the handling of the spatial projection. If you are only interested in the coordinate cleaning, this should still work

**Comment by azizka** [comment]
Closing this now
