### ISSUE TITLE
Error in outlier test in clean_coordinates() 

### ISSUE THREAD

**Issue by damariszurell** [ropensci/CoordinateCleaner#47]
Hi there,
It seems this issue has been reported before, but still causes troubles.

Specifically, the outlier test in clean_coordinates() throws an error while cc_outl() works alright.

---
SessionInfo: R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

other attached packages:
 CoordinateCleaner_2.0-15 
 rgbif_3.2.0   

---
Example code
```{r}
library(rgbif)
gbif_shrew <- occ_search(scientificName = "Sorex alpinus")$data

library(CoordinateCleaner)
gbif_shrew <- subset(gbif_shrew, !is.na(decimalLatitude))
clean_coordinates(gbif_shrew, lon="decimalLongitude", lat="decimalLatitude", tests="outliers")
```
# produces the following error:

cc_outl(gbif_shrew, lon="decimalLongitude", lat="decimalLatitude")

**Comment by azizka** [comment]
Closing this, since it is duplicated from #48
