### ISSUE TITLE
Error in outlier test in clean_coordinates() 

### ISSUE THREAD

**Issue by damariszurell** [ropensci/CoordinateCleaner#48]
Hi there,
It seems this issue has been reported before, but still causes troubles.

Specifically, the outlier test in clean_coordinates() throws an error while cc_outl() works alright.

---
SessionInfo: R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

other attached packages:
 CoordinateCleaner_2.0-15 
 rgbif_3.2.0   

---
Example code
```{r}
library(rgbif)
gbif_shrew <- occ_search(scientificName = "Sorex alpinus")$data

library(CoordinateCleaner)
gbif_shrew <- subset(gbif_shrew, !is.na(decimalLatitude))
clean_coordinates(gbif_shrew, lon="decimalLongitude", lat="decimalLatitude", tests="outliers")
```
produces the following error:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/22585618/89885529-7f5f0880-dbcb-11ea-81a3-b9e451f179d8.png">

```{r}
# This works alright:
cc_outl(gbif_shrew, lon="decimalLongitude", lat="decimalLatitude")
```

**Comment by azizka** [comment]
Hi!
Hm this works for me under CoordinateCleaner v2.0-16. Since you use v2.0-15, could you try to install the latest version, and report if the problem persists?

```{r}
library(devtools)
install_github("ropensci/CoordinateCleaner")
```
Thanks!

**Comment by damariszurell** [comment]
Thanks, it works fine with CoordinateCleaner v2.0-16 !

**Comment by azizka** [comment]
Great!
