### ISSUE TITLE
Error: package or namespace load failed for ‘CoordinateCleaner’ 

### ISSUE THREAD

**Issue by Marialejandra** [ropensci/CoordinateCleaner#74]
Hello! I am trying to run your script, but I am having a couple of problems. 

>>First, when I tried to call the Library CoordinateCleaner I had this error:
Error: package or namespace load failed for ‘CoordinateCleaner’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘terra’

>>I tried to download the package terra using install. package, but and I had this error:
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’

>>I was able to run the first part of the script without any problem, but when I try to use the function clean_coordinates (flag the problematic records) I am having this error: 
Error in clean_coordinates(x = dat_hj, lon = "decimalLongitude", lat = "decimalLatitude",  : 
  could not find function "clean_coordinates"

Can you help me? Thank you so much!!

**Comment by BrunoVilela** [comment]
Hi @Marialejandra, the new version is now on GitHub and this issue should have been fixed as we removed the dependency on rgdal, please let us know if the problems persists.
