### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [ropensci/CoordinateCleaner#78]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by Pseudomys** [comment]
Seconded. In the meantime, is it possible to still use this package (I'm wanting to use function cc_outl just now) with rgdal now retired?

**Comment by azizka** [comment]
working on this, but will take some time.

**Comment by rsbivand** [comment]
New blog: https://r-spatial.org/r/2023/04/10/evolution3.html. This strong dependence on retiring packages is a problem for a package depending on this package: https://github.com/brunobrr/bdc/issues/253, and will be a problem for any workflows using the package. Best completed in June 2023, last gasp October 2023. In NAMESPACE, you have:
```
importFrom(rgdal,readOGR) # use st_read() and coerce to sp
importFrom(rgeos,gBuffer) # use st_buffer coercing to sf and back to sp
importFrom(sp,"proj4string<-") # ensure use of WKT-2
importFrom(sp,CRS) # uses st_crs internally in status 2L
importFrom(sp,disaggregate) # probably defunct
importFrom(sp,over) # probably defunct
importFrom(sp,proj4string) # ensure use of WKT-2
importFrom(sp,spTransform) # uses st_transform internally in status 2L
```
Whether these are actually used or not is unknown, only `rgeos::gBuffer` was found by `pkgapi`. I would drop the strong dependencies, comment out the imports, then work around the problems then arising until the output matches the output before changes.

I don't see any relevant updates to the github repo, but maybe you have already made changes on a clone or fork. Since this is an ropensci package, I suggest a review round with them, perhaps also to check workflows not published as packages. @maelle , @Bisaloo suggestions? If you need to raise issues with us, please use https://github.com/r-spatial/evolution/issues.

**Comment by azizka** [comment]
@BrunoVilela has started working on this,this week, will be finished before October These hint will be very helpful, thanks.

**Comment by rsbivand** [comment]
Now only three months remain, please submit to CRAN soon @BrunoVilela @kguidonimartins  https://github.com/brunobrr/bdc/issues/253

**Comment by maelle** [comment]
I followed up with the maintainer per email.

**Comment by rsbivand** [comment]
@maelle Thanks!

**Comment by rsbivand** [comment]
@azizka @maelle @BrunoVilela The current state of the `new_spatial` branch passes my `CMD check` with the forthcoming changes. Please expedite submission to CRAN, as the current release will fail when `sp` 2.1-0 is submitted (hopefully in early September), freeing `sp` from the retiring packages.

**Comment by rsbivand** [comment]
@azizka @maelle @BrunoVilela Action needed immediately; the package will fail CRAN checks as soon as `sp` 2.1-0 is published, (very soon); `rgdal` and `rgeos` have less than three weeks' left.

**Comment by azizka** [comment]
Thanks, we are working through the issues. Target date was end of this month. @BrunoVilela any news?

**Comment by rsbivand** [comment]
@azizka Thanks, please try to complete ASAP to avoid a last minute rush. We expect to archive the retiring packages 16 October.

**Comment by maelle** [comment]
@azizka @BrunoVilela any news? It might be too late to avoid an archival on CRAN now.

**Comment by rsbivand** [comment]
@maelle 3.0 was published on CRAN 2023-10-03, looks OK, closing here, thanks for your cooperation.

**Comment by maelle** [comment]
:tada: :relieved:
