### ISSUE TITLE
Installation failure due to version of R

### ISSUE THREAD

**Issue by kguidonimartins** [ropensci/CoordinateCleaner#8]
I can not install this package because the version of R described in the DESCRIPTION file is 3.5.1. I use a machine with Ubuntu 16.04, and the latest version of R available is 3.4.4, yet.

Is there any other way to install this package? I've already tried CRAN and `devtools`.

**Comment by dmcglinn** [comment]
Unless there is a really good reason I would also request that the R version requirement be relaxed.

**Comment by dmcglinn** [comment]
@kguidonimartins did you find a way to get around #7 which is related to installing the dependency units on ubuntu.

**Comment by kguidonimartins** [comment]
I had no problems with units. Did you check this issue? https://github.com/r-quantities/units/issues/1

**Comment by azizka** [comment]
I will close the issue, since it seems rather related to the units package

**Comment by kguidonimartins** [comment]
OK, @azizka! But let me explain: this issue was not related to units package. Instead, this issue was related to the DESCRIPTION file in which R version is 3.5.0. Some Linux machine, especially Debian ones, had the 3.5.0 R version released just eight days after this issue was opened.
