### ISSUE TITLE
Check for range_rad is incorrect

### ISSUE THREAD

**Issue by joelnitta** [ropensci/CoordinateCleaner#85]
There is a bug in `clean_coordinates()` where the check for the `range_rad` argument is wrong: it issues an error if `range_rad` is **not** `NULL`, when the error should be if `rand_rad` **is** `NULL`:

https://github.com/ropensci/CoordinateCleaner/blob/93364d0acfcc40ae0b46a0c7b99b7ced7bffe53d/R/clean_coordinates.R#L345-L346

**Comment by BrunoVilela** [comment]
Hi @joelnitta! thanks for pointing this out. The issue has now been fixed in the new version available on Github.
