### ISSUE TITLE
Error in cc_sea when using seas_ref  = buffland

### ISSUE THREAD

**Issue by jaum20** [ropensci/CoordinateCleaner#94]
cc_sea(df, lon = "decimalLongitude.new1",
       lat = "decimalLatitude.new1", ref = buffland)

```
Testing sea coordinates
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘geomtype’ for signature ‘"PackedSpatVector"’
```

If I omit `ref = buffland`, it works fine

**Comment by AMBarbosa** [comment]
As per the `?cc_sea` help file, `ref` should be a SpatVector of polygons. And, like your error message says, the method is not impemented for a PackedSpatVector. Try unpacking it first with `buffland <- unwrap(buffland)`.

**Comment by jaum20** [comment]
I am almost sure this was not necessary in the 2.0 version. Thank you
